### PR TITLE
chore: Use Travis for Windows tests

### PR DESCRIPTION
**Pull request by demurgos**
This commit updates the CI config to only use Travis for both Linux and Windows tests. It means that it removes the integration with AppVeyor.

### CODE REVIEW

**Comment by demurgos** [comment]
The tests hang on Windows. I'll have to take a closer look at the issue.

**Comment by demurgos** [comment]
Fixed, the issue was caused by the test command missing the file glob.

**Comment by coreyfarrell** [comment]
I posted a bug at tapjs/node-tap#554, as far as I know the glob is not supposed to be required for tapjs@13.  Either way this gets us testing on Windows so I'll merge even if we later remove the glob.

**Comment by isaacs** [comment]
The regexp on windows issue is fixed in tap v13.1.10 https://github.com/tapjs/node-tap/commit/a9bd8f301e8e3e265b0c4cd40a2badd1d00ad09f

**Comment by coreyfarrell** [comment]
@isaacs we're still having the issue after updating tap, see #92.  Any thoughts?

**Pull request merged**
