### PR TITLE
chore: Remove glob from tap command-line

### PR DESCRIPTION
**Pull request by coreyfarrell**
Update to tap@13.1.10 to fix a bug where command-line glob was required
under Windows.

### CODE REVIEW

**Comment by isaacs** [comment]
It works for me locally on windows.  Not sure what's going on with Travis.

```
C:\spawn-wrap>npm t

> spawn-wrap@1.4.2 test C:\spawn-wrap
> tap

 SKIP  test/abs-shebang.js > No proper shebang support on windows, so skip this 648ms
 SKIP  TAP
 ~ test/abs-shebang.js > No proper shebang support on windows, so skip this

 SKIP  test/basic.js
 ~ SIGINT > no signals get through cmd

 SKIP  test/basic.js
 ~ SIGHUP > no signals get through cmd

 PASS  test/double-wrap.js 3 OK 1s
 SKIP  test/basic.js
 ~ SIGINT > no signals get through cmd

 SKIP  test/basic.js
 ~ SIGHUP > no signals get through cmd

 SKIP  test/basic.js
 ~ SIGINT > no signals get through cmd

 SKIP  test/basic.js
 ~ SIGHUP > no signals get through cmd

 SKIP  test/basic.js
 ~ exec shebang > no shebang execution on windows

 SKIP  test/basic.js
 ~ Node 5.8.x + npm 3.7.x - spawn > no shebang execution on windows

 PASS  test/exec-flag.js 2 OK 1s
 SKIP  test/basic.js
 ~ Node 5.8.x + npm 3.7.x - shell > no shebang execution on windows

 SKIP  test/basic.js 9 skip of 34 3s
 ~ SIGINT > no signals get through cmd
 ~ SIGHUP > no signals get through cmd
 ~ SIGINT > no signals get through cmd
 ~ SIGHUP > no signals get through cmd
 ~ SIGINT > no signals get through cmd
 ~ SIGHUP > no signals get through cmd
 ~ exec shebang > no shebang execution on windows
 ~ Node 5.8.x + npm 3.7.x - spawn > no shebang execution on windows
 ~ Node 5.8.x + npm 3.7.x - shell > no shebang execution on windows

 PASS  test/wrap-twice.js 3 OK 1s


  🌈 SUMMARY RESULTS 🌈


 SKIP  test/abs-shebang.js > No proper shebang support on windows, so skip this 648ms
 SKIP  test/basic.js 9 skip of 34 3s
 ~ SIGINT > no signals get through cmd
 ~ SIGHUP > no signals get through cmd
 ~ SIGINT > no signals get through cmd
 ~ SIGHUP > no signals get through cmd
 ~ SIGINT > no signals get through cmd
 ~ SIGHUP > no signals get through cmd
 ~ exec shebang > no shebang execution on windows
 ~ Node 5.8.x + npm 3.7.x - spawn > no shebang execution on windows
 ~ Node 5.8.x + npm 3.7.x - shell > no shebang execution on windows

Suites:   4 passed, 1 skip, 5 of 5 completed
Asserts:  33 passed, 10 skip, of 43
Time:     4s

C:\spawn-wrap>npx tap --version
13.1.10
```

**Comment by coreyfarrell** [comment]
@isaacs Any debug we can enable to troubleshoot further?

**Comment by isaacs** [comment]
Yeh, set `NODE_DEBUG=tap`, and it'll dump a lot of stuff.

**Comment by coreyfarrell** [comment]
Abandon this for now.

**Pull request closed without merging**
